version: "1.0"
services:
  myapp:
    image: demo
    ports:
      - "8080:8080"
prometheus:
  image: quay.io/prometheus/prometheus:v2.0.0
  ports:
    - "9090:9090"
  command: "--config.file=/etc/prometheus/prometheus.yml"
  configs:
    - source: prometheus.yml
      target: /etc/prometheus/prometheus.yml
configs:
  prometheus.yml:
    file: ./prometheus.yml